/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BadgeIcon: typeof import('./src/components/BadgeIcon.vue')['default']
    Button: typeof import('primevue/button')['default']
    copy: typeof import('./src/components/LayoutNotion copy.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Image: typeof import('primevue/image')['default']
    LayoutMessage: typeof import('./src/components/LayoutMessage.vue')['default']
    LayoutNotion: typeof import('./src/components/LayoutNotion.vue')['default']
    LayoutUser: typeof import('./src/components/LayoutUser.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SildeFadeDropDown: typeof import('./src/components/SildeFadeDropDown.vue')['default']
    SlideFadeDropdown: typeof import('./src/components/SlideFadeDropdown.vue')['default']
    SlideFadeDropDown: typeof import('./src/components/SlideFadeDropDown.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
